# Generated by Django 3.2.5 on 2021-09-12 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('centre', models.CharField(max_length=50)),
                ('vaccine_name', models.CharField(max_length=100)),
                ('dose', models.TextField(max_length=10)),
                ('date', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
