# Generated by Django 3.2.5 on 2021-09-12 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaccine_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='vaccine_name',
        ),
    ]
